// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from 'D:/Git/qing-ui/docs/index.md?type=frontmatter';
import { demoIndex as dmi0 } from 'D:/Git/qing-ui/docs/index.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from 'D:/Git/qing-ui/src/alert/index.md?type=frontmatter';
import { demoIndex as dmi1 } from 'D:/Git/qing-ui/src/alert/index.md?type=demo-index';

export const filesMeta = {
  'docs/index': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'D:/Git/qing-ui/docs/index.md?type=text'),
  },
  'components/alert/index': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__alert" */'D:/Git/qing-ui/src/alert/index.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
